### ISSUE TITLE
Problem with importing project

### ISSUE THREAD

**Issue by ghost** [xeleh/enhancer#13]
_"RequestScriptReload"_ wasn't found when in imported the project.
i couldn't fine the veiw for it on the project setting
 im in 2019.2.81f they didn't have a import form a git hub link so i imported it from the download

**_error message_** : 
"\enhancer-master\enhancer-master\Editor\Theme\ThemeManager.cs(99,16): error CS0117: 'EditorUtility' does not contain a definition for 'RequestScriptReload' .

**Comment by xeleh** [comment]
https://github.com/xeleh/enhancer#requirements
