### ISSUE TITLE
Dark Theme Isn't There, Only SideBar!!

### ISSUE THREAD

**Issue by Bump-Dev** [xeleh/enhancer#14]
![image](https://user-images.githubusercontent.com/66213003/90328660-db000c00-dfa6-11ea-8609-6a9314819380.png)

**Comment by xeleh** [comment]
As indicated in the readme, the dark theme feature was disabled for Unity 2019.3.15+ because Unity "fixed the problem".

**Good news is that starting in 2019.4.8 / 2020.1 the dark theme is now free for all users.**

https://forum.unity.com/threads/dark-theme-is-free-2019-4-8.950410/

**Comment by Bump-Dev** [comment]
oh ok, thanks! :D
