### ISSUE TITLE
Dark theme menu not appeared for me in personal account 2019.4.6f1

### ISSUE THREAD

**Issue by PradeepHGK** [xeleh/enhancer#15]
* Unity **2019.4.6f1**
* I have imported the package
* I am `not getting` enable dark mode option in editor enhancer. 

<img width="961" alt="EditorEnhancer" src="https://user-images.githubusercontent.com/22808627/91078941-05199400-e661-11ea-81e5-b420b0b4e349.png">

can somebody help me on this?

**Comment by xeleh** [comment]
See https://github.com/xeleh/enhancer/issues/14 ;)
