### ISSUE TITLE
The editor backround converts back to lightmode after going into playmode for 5+ times. Version 2019.3.0a.

### ISSUE THREAD

**Issue by intellichicken** [xeleh/enhancer#3]
After going into playmode for 5+ times the backround of the editor coverts back to light mode while icons remain as dark mode icons. To get around this, I have to turn off dark mode and turn it on again in the editor enhancer.

**Comment by kamyker** [comment]
why would you use 2019.3.0a ?

**Comment by intellichicken** [comment]
> why would you use 2019.3.0a ?

It's the latest version I had because using unity 2020 messed up my whole editor with this.

**Comment by kamyker** [comment]
Don't use alpha/beta of 2019... there's no point.
