### ISSUE TITLE
Unity 2019.3.15f1 - broken

### ISSUE THREAD

**Issue by skaraman** [xeleh/enhancer#9]
The package does not "dark theme" style the latest release version of Unity appropriately.

**Comment by xeleh** [comment]
Yeah, the party is over. You can thank Unity for "fixing the problem".

![Screenshot 2020-05-28 at 23 41 40](https://user-images.githubusercontent.com/148356/83196913-fa706100-a13c-11ea-8941-0cf27da6b7fc.png)

https://unity3d.com/unity/whats-new/2019.3.15

**Comment by skaraman** [comment]
> Yeah, the party is over. You can thank Unity for "fixing the problem".
> 
> 
> 
> ![Screenshot 2020-05-28 at 23 41 40](https://user-images.githubusercontent.com/148356/83196913-fa706100-a13c-11ea-8941-0cf27da6b7fc.png)
> 
> 
> 
> https://unity3d.com/unity/whats-new/2019.3.15
> 
> 
> 
> 

I thought their approach was “we definitely don’t want to do anything to restrict ui styling/skinning” oh well.
